# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - customerchurnpredictionproject

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://dockerchurnprediction.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_f2d68e5cf5a24b3fbd16ba4cbe9e04fc }}
        password: ${{ secrets.AzureAppService_ContainerPassword_a6750c32eef04e1fbbadc064191b9b5d }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: dockerchurnprediction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f2d68e5cf5a24b3fbd16ba4cbe9e04fc }}/customerchurnpredictionproject:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'customerchurnpredictionproject'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6d433ffa2fcf4971a28c11bf7deac252 }}
        images: 'dockerchurnprediction.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_f2d68e5cf5a24b3fbd16ba4cbe9e04fc }}/customerchurnpredictionproject:${{ github.sha }}'